// Mocks generated by Mockito 5.3.0 from annotations
// in imdb_sample/test/ui/providers/popular_movies/popular_movies_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flutter/foundation.dart' as _i3;
import 'package:hive_flutter/hive_flutter.dart' as _i7;
import 'package:imdb_sample/data/models/domain/movie.dart' as _i6;
import 'package:imdb_sample/data/models/persistence/db_movie.dart' as _i8;
import 'package:imdb_sample/data/models/responses/popular_movies_response.dart'
    as _i2;
import 'package:imdb_sample/data/repositories/movies_repository.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePopularMoviesResponse_0 extends _i1.SmartFake
    implements _i2.PopularMoviesResponse {
  _FakePopularMoviesResponse_0(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

class _FakeValueListenable_1<T> extends _i1.SmartFake
    implements _i3.ValueListenable<T> {
  _FakeValueListenable_1(Object parent, Invocation parentInvocation)
      : super(parent, parentInvocation);
}

/// A class which mocks [MoviesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMoviesRepository extends _i1.Mock implements _i4.MoviesRepository {
  MockMoviesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i6.Movie>> fetchPopularMoviesPage(int? page) =>
      (super.noSuchMethod(Invocation.method(#fetchPopularMoviesPage, [page]),
              returnValue: _i5.Future<List<_i6.Movie>>.value(<_i6.Movie>[]))
          as _i5.Future<List<_i6.Movie>>);
  @override
  List<_i6.Movie> getPersistPopularMoviesByPage(int? page) => (super
      .noSuchMethod(Invocation.method(#getPersistPopularMoviesByPage, [page]),
          returnValue: <_i6.Movie>[]) as List<_i6.Movie>);
  @override
  _i5.Future<_i2.PopularMoviesResponse> getRemoteMoviesByPage(int? page) =>
      (super.noSuchMethod(Invocation.method(#getRemoteMoviesByPage, [page]),
              returnValue: _i5.Future<_i2.PopularMoviesResponse>.value(
                  _FakePopularMoviesResponse_0(
                      this, Invocation.method(#getRemoteMoviesByPage, [page]))))
          as _i5.Future<_i2.PopularMoviesResponse>);
  @override
  _i5.Future<_i6.Movie?> toggleFavourite(int? movieId) => (super.noSuchMethod(
      Invocation.method(#toggleFavourite, [movieId]),
      returnValue: _i5.Future<_i6.Movie?>.value()) as _i5.Future<_i6.Movie?>);
  @override
  _i3.ValueListenable<_i7.Box<_i8.DBMovie>> getMovieListenable(int? id) =>
      (super.noSuchMethod(Invocation.method(#getMovieListenable, [id]),
              returnValue: _FakeValueListenable_1<_i7.Box<_i8.DBMovie>>(
                  this, Invocation.method(#getMovieListenable, [id])))
          as _i3.ValueListenable<_i7.Box<_i8.DBMovie>>);
  @override
  _i3.ValueListenable<_i7.Box<_i8.DBMovie>> getPopularMoviesListenable() =>
      (super.noSuchMethod(Invocation.method(#getPopularMoviesListenable, []),
              returnValue: _FakeValueListenable_1<_i7.Box<_i8.DBMovie>>(
                  this, Invocation.method(#getPopularMoviesListenable, [])))
          as _i3.ValueListenable<_i7.Box<_i8.DBMovie>>);
}
